// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore.Scaffolding;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TestNamespace
{
    public static class VectorIndexEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(CompiledModelSqlServerTest.VectorIndexEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Vector>k__BackingField")]
        public static extern ref SqlVector<float>? Vector(CompiledModelSqlServerTest.VectorIndexEntity @this);
    }
}
