name: 🐛 Bug in Microsoft.Data.Sqlite
description: Create a report about something that isn't working in Microsoft.Data.Sqlite.
labels: ["area-adonet-sqlite", "customer-reported"]
body:
  - type: markdown
    attributes:
      value: |-
        Remember:

        * Please check that the [documentation](https://docs.microsoft.com/ef/) does not explain the behavior you are seeing.
        * Please search in both [open](https://github.com/dotnet/efcore/issues) and [closed](https://github.com/dotnet/efcore/issues?q=is%3Aissue+is%3Aclosed) issues to check that your bug has not already been filed.
  - type: textarea
    id: description
    attributes:
      label: Bug description
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Your code
      description: |-
        To fix any bug we must first reproduce it. To make this possible, please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing.

        It is often impossible for us to reproduce a bug when working with only code snippets since we have to guess at the missing code. 
      render: csharp
    validations:
      required: true
  - type: textarea
    id: stack
    attributes:
      label: Stack traces
      description: |-
        Include the full exception message and stack trace for any exception you encounter. 
      render: text
    validations:
      required: false
  - type: input
    id: version-mds
    attributes:
      label: Microsoft.Data.Sqlite version
      placeholder: |-
        9.0.0
    validations:
      required: true
  - type: input
    id: version-target
    attributes:
      label: Target framework
      placeholder: |-
        .NET 9.0
    validations:
      required: false
  - type: input
    id: version-os
    attributes:
      label: Operating system
      placeholder: |-
        Windows 11
    validations:
      required: false
