// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TestNamespace
{
    public partial class DbContextModel
    {
        private DbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("00000000-0000-0000-0000-000000000000"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var fullTextEntity = FullTextEntityEntityType.Create(this);

            FullTextEntityEntityType.CreateAnnotations(fullTextEntity);

            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var fullTextEntity = FindEntityType("Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelSqlServerTest+FullTextEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            fullTextEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase = new TableBase("Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelSqlServerTest+FullTextEntity", null, relationalModel);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "int", microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase);
            microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase.Columns.Add("Id", idColumnBase);
            var titleColumnBase = new ColumnBase<ColumnMappingBase>("Title", "nvarchar(450)", microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase)
            {
                IsNullable = true
            };
            microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase.Columns.Add("Title", titleColumnBase);
            relationalModel.DefaultTables.Add("Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelSqlServerTest+FullTextEntity", microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase);
            var microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityMappingBase = new TableMappingBase<ColumnMappingBase>(fullTextEntity, microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase, null);
            microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityTableBase.AddTypeMapping(microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityMappingBase, false);
            defaultTableMappings.Add(microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, fullTextEntity.FindProperty("Id")!, microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)titleColumnBase, fullTextEntity.FindProperty("Title")!, microsoftEntityFrameworkCoreScaffoldingCompiledModelSqlServerTestFullTextEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            fullTextEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var fullTextEntityTable = new Table("FullTextEntity", null, relationalModel);
            var idColumn = new Column("Id", "int", fullTextEntityTable);
            fullTextEntityTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            var titleColumn = new Column("Title", "nvarchar(450)", fullTextEntityTable)
            {
                IsNullable = true
            };
            fullTextEntityTable.Columns.Add("Title", titleColumn);
            titleColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(titleColumn);
            relationalModel.Tables.Add(("FullTextEntity", null), fullTextEntityTable);
            var fullTextEntityTableMapping = new TableMapping(fullTextEntity, fullTextEntityTable, null);
            fullTextEntityTable.AddTypeMapping(fullTextEntityTableMapping, false);
            tableMappings.Add(fullTextEntityTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, fullTextEntity.FindProperty("Id")!, fullTextEntityTableMapping);
            RelationalModel.CreateColumnMapping(titleColumn, fullTextEntity.FindProperty("Title")!, fullTextEntityTableMapping);
            var pK_FullTextEntity = new UniqueConstraint("PK_FullTextEntity", fullTextEntityTable, new[] { idColumn });
            fullTextEntityTable.PrimaryKey = pK_FullTextEntity;
            pK_FullTextEntity.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_FullTextEntity));
            var pK_FullTextEntityKey = RelationalModel.GetKey(this,
                "Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelSqlServerTest+FullTextEntity",
                new[] { "Id" });
            pK_FullTextEntity.MappedKeys.Add(pK_FullTextEntityKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FullTextEntityKey).Add(pK_FullTextEntity);
            fullTextEntityTable.UniqueConstraints.Add("PK_FullTextEntity", pK_FullTextEntity);
            var iX_FullTextEntity_Title = new TableIndex(
            "IX_FullTextEntity_Title", fullTextEntityTable, new[] { titleColumn }, false);
            iX_FullTextEntity_Title.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_FullTextEntity_Title));
            var iX_FullTextEntity_TitleIx = RelationalModel.GetIndex(this,
                "Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelSqlServerTest+FullTextEntity",
                new[] { "Title" });
            iX_FullTextEntity_Title.MappedIndexes.Add(iX_FullTextEntity_TitleIx);
            RelationalModel.GetOrCreateTableIndexes(iX_FullTextEntity_TitleIx).Add(iX_FullTextEntity_Title);
            fullTextEntityTable.Indexes.Add("IX_FullTextEntity_Title", iX_FullTextEntity_Title);
            return relationalModel.MakeReadOnly();
        }
    }
}
